In [1]:
import numpy as np
import sys
sys.path.append('/home/hcleroy/PostDoc/aging_condensates/Simulation/Gillespie/Gillespie_backend/')
sys.path.append('/home/hcleroy/aging_condensate/Gillespie/Gillespie_backend')
sys.path.append('/home/hugo/PostDoc/aging_condensates/Gillespie/Gillespie_backend/')
import Gillespie_backend as gil

In [2]:
# gillespie parameter
Nlinker = 2
ell_tot = 10**3
kdiff = 0.1
Energy = -15

Nprocess = 50
args = [[ell_tot,Energy,kdiff,np.random.randint(1000000),Nlinker,3] for _ in range(Nprocess)]

# argument of the different classes
cluster_arg = tuple([3.]) # max distance
MSD_arg = () # no argument 
ISF_arg = (1.,10) # q_norm, q_num_sample
NRG_arg = ()
PCF_arg = (np.sqrt(ell_tot)/2,50) # max_distance,numb_bin
PCF_L_arg = (ell_tot,30) # max_distance,numb_bin

# Simulation parameters
step_tot = 10**4
#check_steps = 10**2
initial_check_steps = step_tot
coarse_grained_step = 10**2
log_base=1.5

In [3]:
gillespie = gil.Gillespie(ell_tot = ell_tot, rho0=0.,BindingEnergy=Energy,kdiff=kdiff,seed=129874,sliding=False,Nlinker = 2,dimension=3)

In [8]:
print(gillespie.get_F())
print(gillespie.get_ell_coordinates())
print(gillespie.move_types)

-2531.0242469692907
[]
{0: 'unbind', 1: 'diffuse', 2: 'slide', 3: 'bind'}


In [4]:
gillespie.evolve(100)

(array([1, 1, 1, 1, 3, 0, 1, 1, 1, 3, 0, 1, 1, 3, 0, 1, 1, 1, 1, 3, 0, 1,
        1, 1, 1, 1, 1, 3, 0, 1, 1, 1, 1, 3, 0, 1, 3, 0, 1, 1, 1, 1, 1, 3,
        0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 0, 1, 3, 0, 1, 1, 1,
        1, 3, 0, 1, 1, 1, 3, 0, 1, 1, 1, 1, 1, 1, 1, 3, 0, 1, 3, 0, 3, 0,
        1, 1, 1, 3, 0, 1, 1, 1, 1, 1, 1, 1]),
 array([2.81927526e-06, 1.58152884e-06, 1.75599974e-06, 1.08583798e-07,
        5.53622687e-06, 4.27541246e+00, 5.60732631e-06, 9.83848526e-07,
        4.20258634e-06, 1.53682645e-06, 5.85381856e-01, 2.35070854e-06,
        2.07193841e-08, 1.48428272e-06, 7.64399387e-01, 1.67150735e-06,
        5.70834241e-07, 7.54507069e-06, 2.92079475e-08, 2.60026907e-06,
        1.47098519e+00, 3.47113759e-06, 5.55365013e-06, 9.17121206e-06,
        8.35485498e-07, 3.32778823e-07, 1.41929103e-06, 2.00261838e-06,
        3.88166985e-01, 1.09443304e-07, 1.63297665e-06, 5.71899830e-07,
        1.46168025e-06, 1.28250014e-07, 2.92185966e+00, 1.73999558e-07,
        8.

In [5]:
print(gillespie.get_R())
print(gillespie.get_ell())

[]
[1000.]


In [6]:
gillespie.get_r()

array([[ 0.        ,  0.        ,  0.        ],
       [ 5.49725139, -4.22988898, -6.17227422]])

In [7]:
gillespie.get_N_loop()

1